### ISSUE TITLE
Show socials

### ISSUE THREAD

**Issue by penalosa** [freshairradio/api#3]
Shows have the option to give links to their social media accounts, and the social media icons above their show description should link to the right place. The option to edit these is exposed in the show management UI, and they're available at `{show}.meta.facebook`, `{show}.meta.twitter` etc...

**Comment by penalosa** [comment]
Each show also has an RSS feed at `https://api.freshair.radio/rss/{show_slug}`, which should be linked

**Comment by malavivenkatesh** [comment]
Done, and made the socials only appear if they are added so there aren't any icons without links

**Comment by penalosa** [comment]
Does this cover RSS as well?

**Comment by malavivenkatesh** [comment]
> 
> 
> Does this cover RSS as well?

Yup! RSS is always shown

Edit: Actually the RSS changed but it's a quick fix

**Comment by penalosa** [comment]
Closed by [freshairradio/website](https://github.com/freshairradio/website)
